[[constraint]]
  name = "github.com/pulumi/pulumi"
  version = "v0.15.1"

[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi-terraform"

[[constraint]]
  branch = "master"
  name = "github.com/terraform-providers/terraform-provider-random"
