[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi-terraform"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-random"
  version = "v2.0.0"

  [constraint.metadata]
    govendor-exclude-prefixes = ["github.com/mitchellh/copystructure","github.com/mitchellh/reflectwalk","github.com/golang/protobuf"]
    govendor-override = true

[[override]]
  name = "github.com/mitchellh/copystructure"
  revision = "d23ffcb85de31694d6ccaa23ccb4a03e55c1303f"

[[override]]
  name = "github.com/mitchellh/reflectwalk"
  revision = "63d60e9d0dbc60cf9164e6510889b0db6683d98c"

# NOTE: the following overrides were injected by govendor-override. It may be necessary to
# remove some of these overrides in order to produce a buildable vendor tree.
[[override]]
  name = "github.com/apparentlymart/go-cidr"
  revision = "7e4b007599d4e2076d9a81be723b3912852dda2c"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-rundeck-api"
  revision = "f6af74d34d1ef69a511c59173876fc1174c11f0d"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "=v1.8.34"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/bgentry/go-netrc"
  revision = "9fd32a8b3d3d3f9d43c341bfe098430e07609480"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/blang/semver"
  revision = "2ee87856327ba09384cabd113bc6b5d174e9ec0f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/davecgh/go-spew"
  revision = "346938d642f2ec3594ed81d874461961cd0faa76"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/dustinkirkland/golang-petname"
  revision = "242afa0b4f8af1fa581e7ea7f4b6d51735fa3fef"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/fsouza/go-dockerclient"
  revision = "1d4f4ae73768d3ca16a6fb964694f58dc5eba601"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/go-ini/ini"
  revision = "766e555c68dc8bda90d197ee8946c37519c19409"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/errwrap"
  revision = "7554cd9344cec97297fa6649b055a8c98c2a1e55"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-cleanhttp"
  revision = "3573b8b52aa7b37b9358d966a898feb387f62437"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-getter"
  revision = "c3d66e76678dce180a7b452653472f949aedfbcd"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-multierror"
  revision = "d30f09973e19c1dfcd120b2d9c4f168e68d6b5d5"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-plugin"
  revision = "f72692aebca2008343a9deb06ddb4b17f7051c15"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-uuid"
  revision = "36289988d83ca270bc07c234c36f364b0dd9c9a7"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-version"
  revision = "e96d3840402619007766590ecea8dd7af1292276"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/hcl"
  revision = "a4b07c25de5ff55ad3b8936cea69a79a3d95a855"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/hil"
  revision = "fac2259da677551de1fb92b844c4d020a38d8468"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/logutils"
  revision = "0dc08b1671f34c4250ce212759ebd880f743d883"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/terraform"
  revision = "5bcc1bae5925f44208a83279b6d4d250da01597b"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/yamux"
  revision = "d1caa6c97c9fc1cc9e83bbe34d0603f9ff0ce8bd"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/jmespath/go-jmespath"
  revision = "bd40a432e4c76585ef6b72d3fd96fb9b6dc7b68d"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/go-homedir"
  revision = "b8bc1bf767474819792c23f32d8286a45736f1c6"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/hashstructure"
  revision = "6b17d669fac5e2f71c16658d781ec3fdd3802b69"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/mapstructure"
  revision = "53818660ed4955e899c0bcafa97299a388bd7c8e"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/rancher/go-rancher"
  revision = "ec24b7f12fca9f78fbfcd62a0ea8bce14ade8792"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "b061729afc07e77a8aa4fad0a2fd840958f1942a"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/crypto"
  revision = "b176d7def5d71bdd214203491f89843ed217f420"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/net"
  revision = "1c05540f6879653db88113bc4a2b70aec4bd491f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.6.1"
  [override.metadata]
    govendor-overridden=true
