on:
  push:
    branches:
    - master
    - release-*
    tags:
    - '*.*.*'
  pull_request:
  schedule:
  - cron: 0 2 * * 1-5
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Get Pulumi Scripts
      run: |
        git clone https://github.com/pulumi/scripts ${GOPATH}/src/github.com/pulumi/scripts
        source ${GOPATH}/src/github.com/pulumi/scripts/ci/prepare-environment.sh
        source ${PULUMI_SCRIPTS}/ci/keep-failed-tests.sh
        source ${PULUMI_SCRIPTS}/ci/install-common-toolchain.sh
    - name: Install Pulumi
      run: |
        curl -L https://get.pulumi.com/ | bash
        export PATH=$HOME/.pulumi/bin:$PATH
    - name: Ensure Dependencies
      run: |
        ${PULUMI_SCRIPTS}/ci/ensure-dependencies
      
