env:
  COVERAGE_EXPORT_DIR: ./bin/coverage

jobs:
  generate_coverage_data:
    name: generate_coverage_data
    needs: prerequisites # Previous job after which all necessary components for building tfgen have been acquired
    runs-on: ubuntu-latest
    steps:
    - name: Generate Coverage Data
      run: |
        echo "Coverage output directory: $COVERAGE_EXPORT_DIR"
        make tfgen

  upload_coverage_data:
    name: upload_coverage_data
    needs: generate_coverage_data
    runs-on: ubuntu-latest
    steps:
    - name: Obtain current date & S3 address
      run: |
        currDateTime=$(date +"%Y-%m-%d_%H-%M-%S")
        newSummaryName="summary_${currDateTime}.json"
        s3BucketName="tfgen-coverage-results-36b7864"
        s3KeyName="summaries/${newSummaryName}"
        s3FullURI="s3://${s3BucketName}/${s3KeyName}"
    - name: Rename summary file
      run: mv $COVERAGE_EXPORT_DIR/summary.json $COVERAGE_EXPORT_DIR/$newSummaryName
    - name: Upload results to AWS
      run: aws s3 cp $MainDir/data/coverage/$newSummaryName $s3FullURI --acl bucket-owner-full-control

name: tfgen-coverage-tracking

on:
  pull_request:
